### ISSUE TITLE
Modifications diverses sur le spawn d'avions

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#173]
Vu avec Sharko le 2023.03.23.

Pour pouvoir tranquillement utiliser les commandes de spawn (`-cap` en particulier), on peut envisager ces ajouts / modifications

- reprise des groupes créés par Sharko dans son .miz
- écriture d'un outil inverse de l'injecteur d'avions (pour faire .miz -> settings.lua)
- spawn de CAP avec 
  - wp0 optionnel à basse vitesse et basse altitude
  - vitesses Point 0 M 0.3 Point 1: 350 Kts et point 2 - 3 M0.63 
  - alt par défaut FL270
  - conservation des options avancées du wp1 (de la template)
  - randomisation des formations
- nouvelle commande qui choisit parmi des groupes aléatoirement en fonction de leur catégorisation (easy, hard, etc.)
- modifications du watchdog de CAP
  - gestion partagée des cibles (pas tout le monde sur la même cible)
  - prise en compte des missiles de croisière
- commande `-awacs` qui spawn un awacs avec la bonne mission
  - option `escort <nom de la template>` qui spawn un groupe en escorte
  - option `skynet` par défaut pour les AWACS (ajout par défaut à skynet)
  - option `eplrs` ou `datalink` pour activer le DL (activé par défaut)
- commande `-escortme` qui spawn un groupe d'escorte pour mon appareil

```[tasklist]
### Tasks
- [x] reprise des groupes créés par Sharko dans son .miz
- [x] écriture d'un outil inverse de l'injecteur d'avions
- [x] modifications du comportement des spawn de CAP
- [ ] #187
- [x] nouvelle commande qui choisit parmi des groupes aléatoirement en fonction de leur catégorisation (easy, hard, etc.)
- [ ] #188
- [ ] #189
```

[Template_cap.miz.zip](https://github.com/VEAF/VEAF-Mission-Creation-Tools/files/11051574/Template_cap.miz.zip)

**Comment by veaf-Sharko** [comment]
commande -awacs qui spawn un awacs avec la bonne mission 
si possible eplrs On de base sinon devoir specifier eplrsOff

**Comment by veaf-Sharko** [comment]
Randomiser les Formations si jamais les formations pre-reglée ne sont pas conservées

**Comment by veaf-Sharko** [comment]
prendre en compte la catégorie missiles dans la gestion partagée de cibles

**Comment by davidp57** [comment]
@veaf-Sharko pour la randomisation de la formation c'est pas trop possible. Mais elle sera dans les options du 1er WP de la template, de toute manière, et ça on le garde.

**Comment by veaf-Sharko** [comment]
Revue
-cap XXX , soucis de vitesse lorsque pas de bleu , les avions orbit pleine PC reduisant d autant leurs temps de vol

**Comment by davidp57** [comment]
Régler les vitesses au mach : 
- 0.3
- 0.5
- 0.63
- 0.63

**Comment by davidp57** [comment]
Grinder 20nm + zone d'engagement 60nm de rayon

**Comment by davidp57** [comment]
Prendre en compte l'aspect pour le calcul de la priorité et définit une priorité max (min?) pour ne pas engager n'importe quoi (en fonction de la mission - escort vs cap)

**Comment by davidp57** [comment]
Pour l'escorte tester la task escort de DCS (elle n'est pas mise par défaut) ou utiliser le watchdog autour de l'avion escorté.
![image](https://user-images.githubusercontent.com/172286/229345250-d70a2da7-02de-4dcd-9f5e-83287ac6b10f.png)

**Comment by davidp57** [comment]
J'ai ajouté des issues techniques pour les points restants
