### ISSUE TITLE
Utilisation de `trigger.action.outTextForUnit`

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Mission-Creation-Tools#199]
```[tasklist]
### Tasks
- [x] modifier `veaf.outTextForUnit()`
- [ ] vérifier dans le code où on utilise trigger.action.outTextForGroup et qu'on veut en fait envoyer à une unité
- [ ] modifier le `/send` du serveur pour permettre l'envoi à un joueur en particulier
```
